<?
$aMenuLinks = Array(
    array(
        "Оплата",
        "#WIZARD_SITE_DIR#/",
        array(),
        array(),
        "",
    ),
    array(
        "Компания",
        "#WIZARD_SITE_DIR#about/",
        array(),
        array(),
        "",
    ),
    array(
        "Контакты",
        "#WIZARD_SITE_DIR#contacts/",
        array(),
        array(),
        "",
    ),
    array(
        "Сервисы",
        "#WIZARD_SITE_DIR#services/",
        array(),
        array(),
        "",
    ),
);
?>