<? require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Поиск"); ?>

<?$APPLICATION->IncludeComponent(
	"bitrix:search.page", 
	"custom", 
	array(
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_TIME" => "3600",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "N",
		"DEFAULT_SORT" => "rank",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FILTER_NAME" => "",
		"NO_WORD_LOGIC" => "N",
		"PAGER_SHOW_ALWAYS" => "Y",
		"PAGER_TEMPLATE" => "custom",
		"PAGER_TITLE" => "Результаты поиска",
		"PAGE_RESULT_COUNT" => "20",
		"PATH_TO_USER_PROFILE" => "",
		"RATING_TYPE" => "",
		"RESTART" => "N",
		"SHOW_RATING" => "",
		"SHOW_WHEN" => "N",
		"SHOW_WHERE" => "N",
		"USE_LANGUAGE_GUESS" => "N",
		"USE_SUGGEST" => "N",
		"USE_TITLE_RANK" => "N",
		"arrFILTER" => array(
			0 => "iblock_catalog",
			1 => "iblock_content",
		),
		"arrFILTER_iblock_catalog" => array(
			0 => $GLOBALS['WEBCOMP']['IBLOCKS']['catalog']['catalog_webcomp'],
		),
		"arrFILTER_iblock_content" => array(
			0 => $GLOBALS['WEBCOMP']['IBLOCKS']['content']['webcomp_market_content_articles'],
			1 => $GLOBALS['WEBCOMP']['IBLOCKS']['content']['webcomp_market_content_brands'],
			2 => $GLOBALS['WEBCOMP']['IBLOCKS']['content']['webcomp_market_content_news'],
			3 => $GLOBALS['WEBCOMP']['IBLOCKS']['content']['webcomp_market_content_offers'],
			4 => $GLOBALS['WEBCOMP']['IBLOCKS']['content']['webcomp_market_content_projects'],
			5 => $GLOBALS['WEBCOMP']['IBLOCKS']['content']['webcomp_market_content_services'],
			6 => $GLOBALS['WEBCOMP']['IBLOCKS']['content']['webcomp_market_content_works'],
		),
		"arrWHERE" => "",
		"COMPONENT_TEMPLATE" => "custom",
		"SHOW_ITEM_TAGS" => "Y",
		"TAGS_INHERIT" => "Y",
		"SHOW_ITEM_DATE_CHANGE" => "Y",
		"SHOW_ORDER_BY" => "Y",
		"SHOW_TAGS_CLOUD" => "N",
		"STRUCTURE_FILTER" => "structure",
		"NAME_TEMPLATE" => "",
		"SHOW_LOGIN" => "Y",
		"TAGS_SORT" => "NAME",
		"TAGS_PAGE_ELEMENTS" => "150",
		"TAGS_PERIOD" => "",
		"TAGS_URL_SEARCH" => "",
		"FONT_MAX" => "50",
		"FONT_MIN" => "10",
		"COLOR_NEW" => "000000",
		"COLOR_OLD" => "C8C8C8",
		"PERIOD_NEW_TAGS" => "",
		"SHOW_CHAIN" => "Y",
		"COLOR_TYPE" => "Y",
		"WIDTH" => "100%"
	),
	false
);?><br><? require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php"); ?>
