<?
$aMenuLinks = [
    [
        "Документы",
        "/company/documents/",
        [],
        [],
        "",
    ],
    [
        "Проекты",
        "/company/projects/",
        [],
        [],
        "",
    ],
    [
        "Гарантия на товар",
        "/company/warranty/",
        [],
        [],
        "",
    ],
    [
        "Отзывы",
        "/company/reviews/",
        [],
        [],
        "",
    ],
    [
        "Статьи",
        "/company/articles/",
        [],
        [],
        "",
    ],
    [
        "Новости",
        "/company/news/",
        [],
        [],
        "",
    ],
];
